# Generated by Django 2.0.6 on 2018-07-05 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currentweather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt', models.IntegerField(blank=True, null=True)),
                ('dt_iso', models.DateTimeField(blank=True, null=True)),
                ('city_id', models.IntegerField(blank=True, null=True)),
                ('temp', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('temp_min', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('temp_max', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('pressure', models.IntegerField(blank=True, null=True)),
                ('humidity', models.IntegerField(blank=True, null=True)),
                ('wind_speed', models.IntegerField(blank=True, null=True)),
                ('wind_deg', models.IntegerField(blank=True, null=True)),
                ('rain_1h', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('rain_3h', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('rain_24h', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('rain_today', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('snow_1h', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('snow_3h', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('snow_24h', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('snow_today', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('clouds_all', models.IntegerField(blank=True, null=True)),
                ('weather_id', models.IntegerField(blank=True, null=True)),
                ('weather_main', models.CharField(blank=True, max_length=50, null=True)),
                ('weather_description', models.CharField(blank=True, max_length=80, null=True)),
                ('weather_icon', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'currentWeather',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Holidays',
            fields=[
                ('date', models.DateTimeField(primary_key=True, serialize=False)),
                ('type', models.CharField(blank=True, max_length=15, null=True)),
                ('timestamp', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'holidays',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Leavetimes',
            fields=[
                ('dayofservice', models.DateTimeField(primary_key=True, serialize=False)),
                ('tripid', models.IntegerField()),
                ('progrnumber', models.SmallIntegerField()),
                ('stoppointid', models.SmallIntegerField(blank=True, null=True)),
                ('plannedtime_arr', models.IntegerField(blank=True, null=True)),
                ('plannedtime_dep', models.IntegerField(blank=True, null=True)),
                ('actualtime_arr', models.IntegerField(blank=True, null=True)),
                ('actualtime_dep', models.IntegerField(blank=True, null=True)),
                ('suppressed', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'leavetimes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Routes',
            fields=[
                ('routes', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'routes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RoutesStopid',
            fields=[
                ('busroute', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('stopid', models.IntegerField()),
            ],
            options={
                'db_table': 'routes_stopid',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Stopsstatic',
            fields=[
                ('index', models.IntegerField(blank=True, null=True)),
                ('stop_id', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('stop_name', models.CharField(blank=True, max_length=100, null=True)),
                ('stop_lat', models.DecimalField(blank=True, decimal_places=20, max_digits=25, null=True)),
                ('stop_long', models.DecimalField(blank=True, decimal_places=20, max_digits=25, null=True)),
                ('true_stop_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'stopsStatic',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Trips',
            fields=[
                ('dayofservice', models.DateTimeField(primary_key=True, serialize=False)),
                ('tripid', models.IntegerField()),
                ('lineid', models.CharField(blank=True, max_length=10, null=True)),
                ('routeid', models.CharField(blank=True, max_length=20, null=True)),
                ('direction', models.IntegerField(blank=True, null=True)),
                ('plannedtime_arr', models.IntegerField(blank=True, null=True)),
                ('plannedtime_dep', models.IntegerField(blank=True, null=True)),
                ('actualtime_arr', models.IntegerField(blank=True, null=True)),
                ('actualtime_dep', models.IntegerField(blank=True, null=True)),
                ('supressed', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'trips',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Weather',
        ),
    ]
