# Generated by Django 2.0.6 on 2018-07-09 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180705_1539'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allstops',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(blank=True, null=True)),
                ('stop_id', models.CharField(max_length=12)),
                ('stop_name', models.CharField(blank=True, max_length=100, null=True)),
                ('stop_lat', models.DecimalField(blank=True, decimal_places=20, max_digits=25, null=True)),
                ('stop_long', models.DecimalField(blank=True, decimal_places=20, max_digits=25, null=True)),
                ('true_stop_id', models.IntegerField(blank=True, null=True)),
                ('busroute', models.CharField(max_length=15)),
                ('stopid', models.IntegerField()),
            ],
            options={
                'db_table': 'allstops',
                'managed': False,
            },
        ),
    ]
