# Generated by Django 2.0.6 on 2018-07-13 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_allstops'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forecastweather',
            fields=[
                ('dt', models.IntegerField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('temp', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('temp_min', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('temp_max', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('pressure', models.IntegerField(blank=True, null=True)),
                ('humidity', models.IntegerField(blank=True, null=True)),
                ('wind_speed', models.IntegerField(blank=True, null=True)),
                ('wind_deg', models.IntegerField(blank=True, null=True)),
                ('clouds_all', models.IntegerField(blank=True, null=True)),
                ('weather_id', models.IntegerField(blank=True, null=True)),
                ('weather_main', models.CharField(blank=True, max_length=50, null=True)),
                ('weather_description', models.CharField(blank=True, max_length=80, null=True)),
                ('weather_icon', models.CharField(blank=True, max_length=10, null=True)),
                ('dt_txt', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'forecastWeather',
                'managed': False,
            },
        ),
    ]
