# Generated by Django 2.0.6 on 2018-07-13 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_forecastweather'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColumnSequence',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('number_46a', models.CharField(blank=True, db_column='46A', max_length=45, null=True)),
            ],
            options={
                'db_table': 'column_sequence',
                'managed': False,
            },
        ),
    ]
