# Generated by Django 2.0.6 on 2018-07-27 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_columnsequence'),
    ]

    operations = [
        migrations.CreateModel(
            name='DublinbusScheduleCurrent',
            fields=[
                ('trip_id', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('arrival_time', models.CharField(blank=True, max_length=45, null=True)),
                ('departure_time', models.CharField(blank=True, max_length=45, null=True)),
                ('stop_id', models.CharField(blank=True, max_length=45, null=True)),
                ('stop_sequence', models.CharField(blank=True, max_length=45, null=True)),
                ('stop_headsign', models.CharField(blank=True, max_length=45, null=True)),
                ('pickup_type', models.CharField(blank=True, max_length=45, null=True)),
                ('drop_off_type', models.CharField(blank=True, max_length=45, null=True)),
                ('shape_dist_traveled', models.CharField(blank=True, max_length=45, null=True)),
                ('route_id', models.CharField(blank=True, max_length=45, null=True)),
                ('service_id', models.CharField(blank=True, max_length=45, null=True)),
                ('shape_id', models.CharField(blank=True, max_length=45, null=True)),
                ('trip_headsign', models.CharField(blank=True, max_length=45, null=True)),
                ('direction_id', models.CharField(blank=True, max_length=45, null=True)),
                ('line_id', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'dublinBus_schedule_current',
                'managed': False,
            },
        ),
    ]
