# Generated by Django 2.0.6 on 2018-08-11 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_coreusersettings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coreusersettings',
            options={},
        ),
    ]
